version: '3'
services:

  # Mysql database container
  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - symfonyNetwork

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - symfonyNetwork

  # Symfony apache project container
  www:
    build: docker/php
    container_name: symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - symfonyNetwork
networks:
  symfonyNetwork:

volumes:
  db-data: